#!/bin/bash

pod() {

## Cleaning up selenium-grid
echo -e "\n************************ Cleaning up selenium-grid ************************************\n"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd oep-e2e-rancher && bash stages/director-gui/selenium-grid-cleanup node '"'$CI_PIPELINE_ID'"''
}

node() {

bash utils/pooling jobname:selenium-grid-deploy
bash utils/e2e-cr jobname:selenium-grid-cleanup jobphase:Running

PIPELINE_ID=$1

{
    cluster1=$(echo "pipeline-$PIPELINE_ID")
    aws cloudformation delete-stack --stack-name selenium-grid-${cluster1}
} || {
    echo 'Selenium CloudFormation stack was absent'
}

bash utils/e2e-cr jobname:selenium-grid-cleanup jobphase:Completed
}

if [ "$1" == "node" ];then
  node $2
else
  pod
fi