#!/bin/bash

pod() {

## Cloning oep-e2e-rancher repo
echo "Cleaning up the cluster *************"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd oep-e2e-rancher && bash stages/cluster-cleanup/cleanup node '"'$master_name'"' '"'$worker1_name'"' '"'$worker2_name'"' '"'$worker3_name'"' '"'$SNAPSHOT_NAME'"''
}

node() {

master_name=$(echo $1)
worker1_name=$(echo $2)
worker2_name=$(echo $3)
worker3_name=$(echo $4)
SNAPSHOT_NAME=$(echo $5)

git clone https://github.com/mayadata-io/litmus.git
cd litmus

## Replace the VM names in csv file
sed -i -e "s/auto1/$master_name/g" \
-e "s/auto2/$worker1_name/g" \
-e "s/auto3/$worker2_name/g" \
-e "s/auto4/$worker3_name/g" k8s/on-prem/openshift-installer/vm_name.csv


## Replace the snapshot name and ESX ip in vars
sed -i -e 's/snapshot_name: "oc-cluster"/snapshot_name: "'$SNAPSHOT_NAME'"/g' \
-e 's/esx_ip: "10.12.1.1"/esx_ip: "10.42.1.1"/g' k8s/on-prem/openshift-installer/vars.yml

ansible-playbook k8s/on-prem/openshift-installer/revert_cluster_state.yml

## Add sleep so that cluster gets ready for next pipeline
sleep 10

## Removimg oep-e2e-rancher repo
cd  && rm -rf oep-e2e-rancher
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5 $6
else
  pod
fi
