#!/bin/bash

pod() {

## Cloning oep-e2e-rancher repo
echo -e "\n************************ Deploying Director On-Prem ***********************************\n"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd oep-e2e-rancher && bash stages/infra-setup/dop node '"'$GITHUB_USERNAME'"' '"'$GITHUB_PASSWORD'"' '"'$DOCKER_USERNAME'"' '"'$DOCKER_PASSWORD'"''
}

node() {

GITHUB_USERNAME=$1
GITHUB_PASSWORD=$2
DOCKER_USERNAME=$3
DOCKER_PASSWORD=$4

bash utils/e2e-cr jobname:dop jobphase:Waiting
bash utils/e2e-cr jobname:dop jobphase:Running
bash utils/e2e-cr jobname:pre-requisites jobphase:Waiting

#####################################
##          Prerequisites          ##
#####################################

echo -e "[ Running Prerequisites ]-------------------------------------\n";

DOP_URL=$(kubectl get nodes -o wide --no-headers | awk {'print $6'} | tail -n 1)

#####################################
##           Deploy DOP            ##
#####################################

echo -e "\n[ Cloning director-charts-internal repo ]--------------------\n"

git clone https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/mayadata-io/director-charts-internal.git

cd director-charts-internal

# Checkout to dop-e2e branch
git checkout dop-e2e

# Get latest directory of helm chart
REPO=$(cat baseline | awk -F',' 'NR==1{print $3}' | awk -F'=' '{print $2}')
TAG=$(cat baseline | awk -F',' 'NR==1{print $NF}' | awk -F'=' '{print $2}')

cd $REPO-$TAG

# Create secret having maya-init repo access
kubectl create secret docker-registry dop-secret --docker-username=$DOCKER_USERNAME --docker-password=$DOCKER_PASSWORD

# Create clusterrolebinding
kubectl create clusterrolebinding kube-admin --clusterrole cluster-admin --serviceaccount=kube-system:default

# Replace mayadataurl with DOP URL used to access DOP in values.yaml
sed 's|url: mayadataurl|url: '$DOP_URL'|' -i ./values.yaml

# Replace storageClass to be used to openebs-hostpath in values.yaml
sed 's/storageClass: standard/storageClass: openebs-hostpath/' -i values.yaml
cat values.yaml

# Remove ingress yamls as ingress is pre-installed in Rancher
cd templates/
rm cm-nginx-configuration.yaml clr-nginx-ingress-clusterrole.yaml cm-tcp-services-ingress.yaml cm-udp-services-ingress.yaml crb-nginx-ingress-clusterrole-nisa-binding.yaml dep-nginx-ingress-controller.yaml ns-ingress-nginx.yaml rlb-nginx-ingress-role-nisa-binding.yaml role-nginx-ingress-role.yaml sa-nginx-ingress-serviceaccount.yaml svc-ingress-nginx.yaml dep-default-http-backend.yaml svc-default-http-backend.yaml
cd ..

# Apply helm chart
helm install --name dop .

# Dump Director On-Prem pods
echo -e "\n[ Dumping Director On-Prem components ]\n"
kubectl get pod

# Exit the directory
cd ../..

bash utils/e2e-cr jobname:dop jobphase:Completed
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi
