#!/bin/bash
pod() {

echo "************* Installing Pre-requisites *************"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd oep-e2e-rancher && bash stages/infra-setup/pre-requisites node'
}

node() {

# Cloning oep-e2e repository which contains all the test scripts
git clone https://github.com/mayadata-io/oep-e2e.git

# Setup litmus on the cluster
kubectl apply -f oep-e2e/litmus/prerequisite/rbac.yaml
kubectl apply -f oep-e2e/litmus/prerequisite/crds.yaml

echo -e "\n************ Finished Prerequisites ************"

}

if [ "$1" == "node" ];then
  node
else
  pod
fi
