#!/bin/bash
pod() {

echo "************* Installing Pre-requisites *************"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd oep-e2e-rancher && bash stages/infra-setup/pre-requisites node'
}

node() {

bash utils/pooling jobname:dop
bash utils/e2e-cr jobname:pre-requisites jobphase:Running



echo -e "\n************ Finished Prerequisites ************"

bash utils/e2e-cr jobname:pre-requisites jobphase:Completed
}

if [ "$1" == "node" ];then
  node
else
  pod
fi
