#!/bin/bash

pod() {

## Deploying selenium--grid
echo -e "\n************************ Deploying selenium-grid **************************************\n"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd oep-e2e-rancher && bash stages/infra-setup/selenium-grid-deploy node '"'$CI_PROJECT_NAME'"' '"'$CI_PIPELINE_ID'"''
}

node() {

CI_PROJECT_NAME=$(echo $1)
CI_PIPELINE_ID=$(echo $2)
GUID=grid-${CI_PROJECT_NAME}-${CI_PIPELINE_ID}
path=$(pwd)

echo -e "\n[ Cloning gui-automation repo ] ------------------------------------\n"
git clone https://$username:$password@github.com/mayadata-io/gui-automation.git
cd gui-automation/scripts/grid
cat scripts/grid/selenium-grid-config.yml

echo -e "\n[ Creating selenium stack ] ----------------------------------------\n"
bash scripts/grid/configure-grid.sh ${GUID} eu-west-2

cd ..
}

if [ "$1" == "node" ];then
  node $2 $3
else
  pod
fi
