#!/bin/bash

pod() {

## Cloning oep-e2e-rancher repo
echo -e "\n************************ Deploying Director On-Prem ***********************************\n"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd oep-e2e-rancher && bash stages/infra-setup/TCID-DIR-INSTALL-ON-LOCAL-HP node '"'$GITHUB_USERNAME'"' '"'$GITHUB_PASSWORD'"' '"'$RELEASE_USERNAME'"' '"'$RELEASE_PASSWORD'"' '"'$RELEASE'"' '"'$CI_JOB_ID'"' '"'$GITHUB_TOKEN'"' '"'$CI_COMMIT_REF_NAME'"''
}

node() {
'"'
GITHUB_USERNAME=$1
GITHUB_PASSWORD=$2
RELEASE_USERNAME=$3
RELEASE_PASSWORD=$4
RELEASE=$5
CI_JOB_ID=$6
GITHUB_TOKEN=$7
CI_COMMIT_REF_NAME=$8

job_id=$(echo $CI_JOB_ID)
gittoken=$(echo "$GITHUB_TOKEN")
current_time=$(date)
branch_name=$CI_COMMIT_REF_NAME
test_name="TCID-DIR-INSTALL-ON-LOCAL-HP"
stage="INFRA-SETUP"
test_desc="Install DOP using helm with SSD underneath"

#####################################
##          Prerequisites          ##
#####################################

echo -e "[ Running Prerequisites ]-------------------------------------\n";

DOP_URL=$(kubectl get nodes -o wide --no-headers | awk {'print $6'} | tail -n 1)

#####################################
##           Deploy DOP            ##
#####################################

echo -e "\n[ Cloning director-charts-internal repo ]--------------------\n"

git clone https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/mayadata-io/director-charts-internal.git

cd director-charts-internal

echo "\n[ Get DOP release version ]-------------------------------------\n"
echo -e "Release Version: $RELEASE\n"

# Get into latest release directory of helm chart
cd "$RELEASE"/director

# Create secret having maya-init repo access
kubectl create secret docker-registry directoronprem-registry-secret --docker-server=registry.mayadata.io --docker-username=$RELEASE_USERNAME --docker-password=$RELEASE_PASSWORD

# Create clusterrolebinding
kubectl create clusterrolebinding kube-admin --clusterrole cluster-admin --serviceaccount=kube-system:default

# Replace storageClass to be used to openebs-hostpath in values.yaml
sed 's/storageClass: standard/storageClass: openebs-hostpath/' -i values.yaml
cat values.yaml

# Apply helm chart
helm install --name dop . --set server.url=$DOP_URL --set nginx-ingress.enabled=false

# Wait for the components to show up
echo -e "\n[ Waiting for the DOP components to show up] ----------------\n"
sleep 600

# Dump Director On-Prem pods
echo -e "\n[ Dumping Director On-Prem components ]\n"
kubectl get pod

# Exit the directory
cd
cd oep-e2e-rancher

echo -e "\n************************ Installing litmus pre-requisites *****************************\n"

# Cloning oep-e2e repository which contains all the test scripts
git clone https://github.com/mayadata-io/oep-e2e.git

# Setup litmus on the cluster
kubectl apply -f oep-e2e/litmus/prerequisite/rbac.yaml
kubectl apply -f oep-e2e/litmus/prerequisite/crds.yaml
kubectl apply -f oep-e2e/litmus/prerequisite/docker-secret.yml

URL=http://$(kubectl get nodes -o wide --no-headers | awk {'print $6'} | tail -n 1)
echo "URL to access DOP: $URL"

# Create a configmap from URL
kubectl create configmap config --from-literal=url=$URL -n litmus

echo -e "\n************************ Running basic-sanity checks **********************************\n"

bash oep-e2e/scripts/director-health-check.sh

# If any of the above check fails, then fail this job
if [ $(cat result.txt | grep -ic fail) != 0 ];then
  testResult="Fail"
  echo -e "\nTest Result: $testResult\n"
  if [[ $branch_name == "oep-release" ]]; then
    python3 oep-e2e/utils/result_update.py --job_id "$job_id" --stage "$stage" --test_desc "$test_desc" --test_result "$testResult" --time_stamp "$current_time" --token "$gittoken" --test_name "$test_name" --job_name "$test_name" --platform "rancher"
  fi
  exit 1
else
  testResult="Pass"
  echo -e "\nTest Result: $testResult\n"
  if [[ $branch_name == "oep-release" ]]; then
    python3 oep-e2e/utils/result_update.py --job_id "$job_id" --stage "$stage" --test_desc "$test_desc" --test_result "$testResult" --time_stamp "$current_time" --token "$gittoken" --test_name "$test_name" --job_name "$test_name" --platform "rancher"
  fi
fi
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5 $6 $7 $8 $9
else
  pod
fi
