#!/bin/bash

pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd oep-e2e-rancher && bash stages/openebs-install/deploy-csi-provisioner node '
}

node() {

export KUBECONFIG=~/.kube/cluster2_config

#pooling over previous job to complete
bash utils/pooling jobname:tcid-dir-op-cstor-pool-recommend-create-stripe
bash utils/e2e-cr jobname:csi-operator-provision jobphase:Running

test_name=$(bash utils/generate_test_name testcase=csi-provision metadata="")
echo $test_name

cd e2e-tests

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | imagePullPolicy   | image  |  Always                             | IfNotPresent                                     |
 | Storage class name| env    | openebs-csi-cstor-sparse            | openebs-cstor-csi                                | 
 | cspc pool name    | env    | rec-create-test                     | rec-create-test                                  | 
  ----------------------------------------------------------------------------------------------------------------------
EOF

echo "Running the litmus test.."
sed -i -e 's/imagePullPolicy: Always/imagePullPolicy: IfNotPresent/g' \
-e 's/value: openebs-csi-cstor-sparse/value: openebs-cstor-csi/g' \
-e 's/cstor-sparse-pool/rec-create-test/g' providers/csi-provisioner/run_litmus_test.yml

run_test=providers/csi-provisioner/run_litmus_test.yml

cat $run_test

bash ../utils/litmus_job_runner label='app:csi-provisioner' job=$run_test

echo "Dumping state of cluster post job run"; echo ""
bash ../utils/dump_cluster_state;

cd ..
bash utils/event_updater jobname:csi-operator-provision $test_name

#################
## GET RESULT  ##
#################
rc_val=$(echo $?)

## Check the test status & result from the litmus result custom resource
source ~/.profile
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

bash utils/e2e-cr jobname:csi-operator-provision jobphase:Completed

if [ "$rc_val" != "0" ]; then
exit 1;
fi

}

if [ "$1" == "node" ];then
  node
else
  pod
fi
